//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NASABAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNasabah
    {
        public string NO_KTP { get; set; }
        public string NAMA_LGKP { get; set; }
        public string ALAMAT { get; set; }
        public string TMPT_LAHIR { get; set; }
        public Nullable<System.DateTime> TGL_LAHIR { get; set; }
        public string NO_HP { get; set; }
    }
}
